DROP TABLE JOB_HISTORY;
DROP TABLE COUNTRIES CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENTS CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEES CASCADE CONSTRAINTS;
DROP TABLE JOBS CASCADE CONSTRAINTS;
DROP TABLE LOCATIONS CASCADE CONSTRAINTS;
DROP TABLE REGIONS CASCADE CONSTRAINTS;

CREATE TABLE COUNTRIES AS SELECT * FROM HR.COUNTRIES;
CREATE TABLE DEPARTMENTS AS SELECT * FROM HR.DEPARTMENTS;
CREATE TABLE EMPLOYEES AS SELECT * FROM HR.EMPLOYEES;
CREATE TABLE JOB_GRADES AS SELECT * FROM HR.JOB_GRADES;
CREATE TABLE JOB_HISTORY AS SELECT * FROM HR.JOB_HISTORY;
CREATE TABLE JOBS AS SELECT * FROM HR.JOBS;
CREATE TABLE LOCATIONS AS SELECT * FROM HR.LOCATIONS;
CREATE TABLE REGIONS AS SELECT * FROM HR.REGIONS;

ALTER TABLE COUNTRIES
    ADD PRIMARY KEY(country_id);
    
ALTER TABLE DEPARTMENTS
    ADD PRIMARY KEY(department_id);
    
ALTER TABLE EMPLOYEES
    ADD PRIMARY KEY(employee_id);
    
ALTER TABLE JOB_GRADES
    ADD PRIMARY KEY(grade);
    
ALTER TABLE JOB_HISTORY
    ADD CONSTRAINT PK_job_history PRIMARY KEY(employee_id, start_date);
    
ALTER TABLE JOBS
    ADD PRIMARY KEY(job_id);
    
ALTER TABLE LOCATIONS
    ADD PRIMARY KEY(location_id);
    
ALTER TABLE REGIONS
    ADD PRIMARY KEY(region_id);

ALTER TABLE COUNTRIES
    ADD FOREIGN KEY (region_id) REFERENCES REGIONS(region_id);
    
ALTER TABLE LOCATIONS
    ADD FOREIGN KEY (country_id) REFERENCES COUNTRIES(country_id);
    
ALTER TABLE JOB_HISTORY
    ADD FOREIGN KEY (job_id) REFERENCES JOBS(job_id);

ALTER TABLE JOB_HISTORY
    ADD FOREIGN KEY (department_id) REFERENCES DEPARTMENTS(department_id);
    
ALTER TABLE DEPARTMENTS
    ADD FOREIGN KEY (location_id) REFERENCES LOCATIONS(location_id);

ALTER TABLE JOB_HISTORY
    ADD FOREIGN KEY (employee_id) REFERENCES EMPLOYEES(employee_id);

ALTER TABLE DEPARTMENTS
    ADD FOREIGN KEY (manager_id) REFERENCES EMPLOYEES(employee_id);

ALTER TABLE EMPLOYEES
    ADD FOREIGN KEY (department_id) REFERENCES DEPARTMENTS(department_id);

ALTER TABLE EMPLOYEES
    ADD FOREIGN KEY (manager_id) REFERENCES EMPLOYEES(employee_id);

ALTER TABLE EMPLOYEES
    ADD FOREIGN KEY (job_id) REFERENCES JOBS(job_id);
    
ALTER TABLE JOB_HISTORY
    ADD FOREIGN KEY (job_id) REFERENCES JOBS(job_id);

ALTER TABLE JOB_HISTORY
    ADD FOREIGN KEY (department_id) REFERENCES DEPARTMENTS(department_id);

ALTER TABLE JOB_HISTORY
    ADD FOREIGN KEY (employee_id) REFERENCES EMPLOYEES(employee_id);

SELECT LAST_NAME || ', ' || SALARY AS WYNAGRODZENIE FROM EMPLOYEES 
WHERE (department_id = 20 OR department_id = 50)
AND (salary >= 2000 AND salary <=7000)
ORDER BY LAST_NAME;

SELECT e.last_name, e.hire_date --third column, tbd
FROM EMPLOYEES e, EMPLOYEES m
WHERE e.manager_id = m.employee_id AND EXTRACT(YEAR FROM m.hire_date) = 2005;
